### ISSUE TITLE
Problem when folder contains quote in name

### ISSUE THREAD

**Issue by Nerothos** [pseudosavant/player.html#17] opened 2022-04-29 14:37 UTC
Hi,

The page doesn't currently handle folder with quote in name (it truncate what's after the quote, quote included)

**Comment by pseudosavant** [comment] 2022-05-03 21:00
Hi @Nerothos, that is interesting. I hadn't run into that yet. Which web server(s) are you using?

Will you please save, and share, copies of your web browser's file browsing pages for the folder, and parent of it, that you have issues with? Like the test examples in this folder? https://github.com/pseudosavant/folder.api/tree/master/server

**Comment by Nerothos** [comment] 2022-05-04 08:03
I'm using Apache/2.4.53
Here's a basic test using an image and a folder with similar quote.

[test.tar.gz](https://github.com/pseudosavant/player.html/files/8618685/test.tar.gz)

**Comment by pseudosavant** [comment] 2022-06-17 16:25
Thanks @Nerothos, I'll check it out when I work on this project next.

**Comment by pseudosavant** [comment] 2022-06-17 19:08
@Nerothos I haven't been able to reproduce this issue using Apache locally with folders that have a quote in them. I checked out your tar file. I don't think I explained what I'm looking for well.

The test examples in https://github.com/pseudosavant/folder.api/tree/master/server are all the result of browsing to a folder on an HTTP server with file browsing enabled and pressing Ctrl-S to save the HTML of the folder/file browsing page. Not the `player.html` page. It is the HTML that the server renders to list the files.

Here is how to do it:
1. Go to the folder that has the problematic folder or file name in it (e.g. http://yourserver.com/videos/)
![image](https://user-images.githubusercontent.com/455424/174386909-bb6544e1-d429-4393-beb0-378de088ccb2.png)
2. Press Ctrl-S to save the `index.html` file of the Apache folder listing
3. Upload that `index.html` here

You should end up with a file like this: https://github.com/pseudosavant/folder.api/blob/master/server/apache-std/index.html

**Comment by pseudosavant** [comment] 2022-06-17 19:32
That file could still be useful for tests, but I figured out where the issue is. Single quotes needed to be percent encoded for URLs in the folder template. The fix will be in the next release.

**Closed by pseudosavant** 2022-06-17 19:32 UTC

**Comment by Nerothos** [comment] 2022-06-24 10:25
Sorry for not responding, I was busy.
I've just tried with that version and it seems to be working ! Thanks.
